#ifndef SRC_COMMON_COMMON_VECTORS_H
#define SRC_COMMON_COMMON_VECTORS_H

#include "vect.h"

VECT_DECLARE_NAME(char *, char_ptr)
VECT_DECLARE_NESTED_PTR_FREE_FOR_NAME(char_ptr)
VECT_DECLARE_NAME(char, char)
VECT_DECLARE_TYPE(size_t)

#endif /* SRC_COMMON_COMMON_VECTORS_H */
